### ISSUE TITLE
support denols

### ISSUE THREAD

**Issue by hemedani** [tamago324/nlsp-settings.nvim#12]
it's because of conflict between `tsserver` and `denols`, in many cases we wan't to disable `tsserver` on Deno project and enable `denols` and vice versa 

Please support [local setting](https://github.com/tamago324/nlsp-settings.nvim/issues/4) and `denols`

this is also happen on [coc-deno](https://github.com/fannheyward/coc-deno) and [vscode Deno extension](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno)

**Comment by tamago324** [comment]
Supported by #14  and https://github.com/neovim/nvim-lspconfig/pull/1611!
