### ISSUE TITLE
Schemas can't load in Windows

### ISSUE THREAD

**Issue by Lopi-py** [tamago324/nlsp-settings.nvim#16]
![image](https://user-images.githubusercontent.com/70210066/148661886-83795409-e482-4b31-ba44-2603cbd483d1.png)
I found the problem, it's on this line https://github.com/tamago324/nlsp-settings.nvim/blob/main/lua/nlspsettings/jsonls.lua#L29, it can be fixed by replacing **file://** with **file:///** or just **/**.
```lua
res[server_name] = string.format('/%s/%s', path, name) -- jsonls.lua L29
```
![image](https://user-images.githubusercontent.com/70210066/148662011-1b3036cd-2c62-4338-a543-3180fa3c48e3.png)
this works fine for me.

**Comment by tamago324** [comment]
PR is welcome!

**Comment by Lopi-py** [comment]
Alright, also I tried in Linux and doesn't seems to work, so I'll do the PR without Windows distinction
