### ISSUE TITLE
NlspConfig for pyright missing autocompletion features

### ISSUE THREAD

**Issue by sperezconesa** [tamago324/nlsp-settings.nvim#26]
Hello everyone!

When I try to make an NlspConfig for pyright, it works nicely but there are some config parameters I can't use.
I am missing some important parameters of pyright configuration in the autocomplete. For example `exclude` that can be found in the [configuration.md](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) of pyright. Adding the `"exclude":"path_to exclude"` doesn't work. If this is not implemented I think it would be a great feature to add.

Thanks for your help and keep up the great work.
Sergio

**Comment by tamago324** [comment]
I think that setting can be configured in `pyrightconfig.json` or `pyproject.toml`.
In nlsp-settings.nvim, only values that can be set in VSCode can be set.

See `contributes.configuration` at [package.json](https://github.com/microsoft/pyright/blob/main/packages/vscode-pyright/package.json).
