### ISSUE TITLE
`williamboman/nvim-lsp-installer` no longer maintained.

### ISSUE THREAD

**Issue by Lazerbeak12345** [tamago324/nlsp-settings.nvim#39]
I think it'd be wise to recommend the successor instead.

Quote from their readme:

> ## ℹ️ Project status
> 
> > This is an excerpt from the [announcement here](https://github.com/williamboman/nvim-lsp-installer/discussions/876).
_`nvim-lsp-installer` is no longer maintained._
> 
> [`mason.nvim`](https://github.com/williamboman/mason.nvim) is the next generation version of `nvim-lsp-installer`. It
builds on top of the very same foundation as `nvim-lsp-installer` (which means it's easy to migrate), but with a
majority of internals refactored to improve extensibility and testability.
> 
> More importantly, the scope of `mason.nvim` has also been widened to target more than just LSP servers. `mason.nvim`
supports DAP servers, linters, formatters, and more. As of writing, `mason.nvim` provides 150+ packages for 100+
languages. It can be thought of as a general-purpose package manager, native to Neovim, that runs everywhere Neovim runs
(Windows, macOS, Linux, etc.).
> 
> Another big change with `mason.nvim` is that executables are now linked to a single, shared, location, allowing seamless
access from Neovim builtins (shell, terminal, etc.) as well as other 3rd party plugins.
> 
> There have also been other improvements such as broader test coverage, more documentation, and a revamped UI - check it
out!

I might be able to rewrite your readme for you, but I don't know how this impacts your code.

**Comment by tamago324** [comment]
We welcome pull request!

**Comment by Lazerbeak12345** [comment]
I re-read the code. Unless I'm mistaken, we're good now.
