### ISSUE TITLE
use the settings file for schemas in jsonls

### ISSUE THREAD

**Issue by ChristianChiarulli** [tamago324/nlsp-settings.nvim#6]
The problem is that this will override your settings that allow you to load the nlsp-settings default schemas

**Comment by tamago324** [comment]
Thank you for your feedback.

The `json.schemas` defined in `jsonls.json` are now merged with the `schemas` specified in `lspconfig."jsonls".setup()`.

**Comment by ChristianChiarulli** [comment]
awesome, thanks
